### ISSUE TITLE
Put through validators

### ISSUE THREAD

**Issue by elamont174** [DesislavaNaydenova/2405-hackathon-team1-StarWars#118]

**Comment by DesislavaNaydenova** [comment]
Put the html code through https://validator.w3.org/ .

- There was a Error on the index.html , which I fixed:
![Image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/152976651/6f09bc8e-09ee-4c41-8456-070cae0643d0)

- There was an Error on the about.html , which should be fixed in the further development:
![Image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/152976651/63a2d090-3d42-40fd-82f9-7a97c2622f40)

- The 404.html didn't show any Errors.

- The quiz.html just dropped a warning:
![Image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/152976651/bc866a6f-030a-4e57-be9a-43345e466bda)

- There were some Errors at the wiki.html , which should be fixed in the further development:
![Image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/152976651/65725137-8c8e-4ec0-ac36-b5f9d73431e9)
![Image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/152976651/f3f7eac1-9129-4441-aa02-bf13e740d9cc)
